export const prompts = {
  "valuable": "The most valuable thing that no one will buy",
  "not-seems": "This is not what it seems",
  "100-bill": "The expression you make when you find a $100 bill hidden inside your Nintendo 64",
  "ice-cream": "The expression you make when your ice cream drops from your cone",
  "gandhi": "Gandhi died for this",
  "lunch": "What is for lunch",
  "yellow": "The yellowest thing",
  "serious": "The most serious book",
  "boring": "The most boring thing",
  "awesome": "The most awesome thing",
  "sad": "The most sad thing",
  "threatening": "The most threatening thing",
  "strong": "The most strong thing",
  "practical": "The most practical thing",
  "cute": "The most cute thing",
  "amusing": "The most amusing thing",
  "wonderful": "The most wonderful thing",
  "impressive": "The most impressive thing",
  "famous": "The most famous thing",
  "ill-informed": "The most ill-informed thing",
  "overrated": "The most overrated thing",
  "stimulating": "The most stimulating thing",
  "suspicious": "The most suspicious thing",
  "tedious": "The most tedious thing",
  "wooden": "The most wooden thing",
  "amused": "The most amused thing",
  "sick": "The most sick thing",
  "unusual": "The most unusual thing",
  "nosy": "The most nosy thing",
  "nutty": "The most nutty thing",
  "ultra": "The most ultra thing",
  "sweltering": "The most sweltering thing",
  "watery": "The most watery thing",
  "fearful": "The most fearful thing",
  "dysfunctional": "The most dysfunctional thing"
}